# Generated by Django 3.1 on 2020-08-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valvulas_Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('state', models.BooleanField(default=False)),
                ('codeStateON', models.CharField(max_length=6)),
                ('codeStateOFF', models.CharField(max_length=6)),
            ],
        ),
    ]
