# Generated by Django 3.1 on 2020-08-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAppW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
