# Generated by Django 3.1 on 2020-08-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAppW', '0002_botones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valvulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valvula1State', models.BooleanField(default=False)),
                ('valvula1StateON', models.CharField(max_length=6)),
                ('valvula1StateOFF', models.CharField(max_length=6)),
                ('valvula2State', models.BooleanField(default=False)),
                ('valvula2StateON', models.CharField(max_length=6)),
                ('valvula2StateOFF', models.CharField(max_length=6)),
            ],
        ),
    ]
