# Generated by Django 3.1 on 2020-08-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webAppW', '0003_valvulas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valvulas',
            old_name='valvula1StateOFF',
            new_name='codeStateOFF',
        ),
        migrations.RenameField(
            model_name='valvulas',
            old_name='valvula1StateON',
            new_name='codeStateON',
        ),
        migrations.RenameField(
            model_name='valvulas',
            old_name='valvula1State',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='valvulas',
            name='valvula2State',
        ),
        migrations.RemoveField(
            model_name='valvulas',
            name='valvula2StateOFF',
        ),
        migrations.RemoveField(
            model_name='valvulas',
            name='valvula2StateON',
        ),
    ]
