# Generated by Django 3.1 on 2020-08-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAppW', '0004_auto_20200816_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvulas',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
