# Generated by Django 3.1 on 2020-08-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webAppW', '0005_valvulas_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Botones',
        ),
    ]
